FROM debian:buster

RUN apt upgrade -y
RUN apt-get update -y


RUN apt-get install vim -y
RUN apt install redis-server -y
RUN apt install wget -y
RUN apt install make gcc -y


RUN apt-get install php-redis -y
COPY ./setup.sh /setup.sh
CMD ["bash","setup.sh"]
