FROM debian:buster

RUN apt-get update -y

RUN apt-get upgrade -y 

EXPOSE 9000

RUN apt install -y vim
RUN apt install -y unzip
RUN apt install -y wget
RUN apt install -y php-fpm php-mysql
RUN apt upgrade -y
RUN mkdir -p /var/www/html
RUN wget https://wordpress.org/latest.zip
RUN unzip latest.zip
RUN rm -rf latest.zip
RUN cp -rf /wordpress/* /var/www/html
RUN service php7.3-fpm start
RUN service php7.3-fpm stop
COPY ./wp-config.php /var/www/html/wordpress/
COPY ./www.conf /etc/php/7.3/fpm/pool.d/
COPY ./php-fpm.conf /etc/php/7.3/fpm/
COPY ./start.sh ./start.sh
ENTRYPOINT ["bash","start.sh"]

